import { StyleSheet, Platform } from 'react-native';
import { Colors } from '@/context/theme-context';

export const getStyles = (isDarkMode: boolean) => {
    const theme = isDarkMode ? 'dark' : 'light';
    const activeColors = Colors[theme];

    return StyleSheet.create({
        container: {
            flex: 1,
            backgroundColor: activeColors.background,
        },
        header: {
            paddingHorizontal: 20,
            paddingTop: 20,
            paddingBottom: 24,
            borderBottomLeftRadius: 24,
            borderBottomRightRadius: 24,
        },
        headerContent: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'flex-start',
            marginBottom: 16,
        },
        headerLeft: {
            flexDirection: 'row',
            alignItems: 'center',
            flex: 1,
        },
        headerIcon: {
            width: 48,
            height: 48,
            borderRadius: 24,
            justifyContent: 'center',
            alignItems: 'center',
            marginRight: 12,
        },
        headerText: {
            flex: 1,
        },
        headerTitle: {
            fontSize: 20,
            fontWeight: '700',
            color: '#ffffff',
            marginBottom: 2,
        },
        headerSubtitle: {
            fontSize: 14,
            color: 'rgba(255, 255, 255, 0.8)',
            fontWeight: '500',
        },
        stepCounter: {
            backgroundColor: 'rgba(255, 255, 255, 0.2)',
            paddingHorizontal: 12,
            paddingVertical: 6,
            borderRadius: 16,
        },
        stepCounterText: {
            fontSize: 14,
            color: '#ffffff',
            fontWeight: '600',
        },
        progressContainer: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
        },
        progressBar: {
            flex: 1,
            height: 6,
            backgroundColor: 'rgba(255, 255, 255, 0.2)',
            borderRadius: 3,
            overflow: 'hidden',
            marginRight: 12,
        },
        progressFill: {
            height: '100%',
            backgroundColor: '#ffffff',
            borderRadius: 3,
        },
        progressText: {
            fontSize: 12,
            color: 'rgba(255, 255, 255, 0.9)',
            fontWeight: '600',
        },
        stepIndicatorContainer: {
            paddingHorizontal: 20,
            paddingVertical: 16,
            backgroundColor: activeColors.card,
            marginHorizontal: 20,
            marginTop: -12,
            borderRadius: 16,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.1,
            shadowRadius: 12,
            elevation: 6,
        },
        stepIndicator: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
        },
        stepItem: {
            flexDirection: 'row',
            alignItems: 'center',
        },
        stepCircle: {
            width: 24,
            height: 24,
            borderRadius: 12,
            backgroundColor: isDarkMode ? '#334155' : '#F3F4F6',
            justifyContent: 'center',
            alignItems: 'center',
        },
        stepCompleted: {
            backgroundColor: '#059669',
        },
        stepCurrent: {
            // backgroundColor set dynamically
        },
        stepLine: {
            width: 24,
            height: 2,
            backgroundColor: isDarkMode ? '#475569' : '#E5E7EB',
            marginHorizontal: 4,
        },
        stepLineCompleted: {
            backgroundColor: '#059669',
        },
        formContainer: {
            flex: 1,
            paddingTop: 20,
        },
        formContent: {
            paddingHorizontal: 20,
        },
        fieldContainer: {
            marginBottom: 20,
        },
        fieldLabel: {
            fontSize: 16,
            fontWeight: '600',
            color: activeColors.text,
            marginBottom: 8,
        },
        required: {
            color: '#DC2626',
        },
        inputContainer: {
            backgroundColor: activeColors.card,
            borderRadius: 12,
            borderWidth: 1,
            borderColor: activeColors.border,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.05,
            shadowRadius: 4,
            elevation: 2,
        },
        disabledInputContainer: {
            backgroundColor: activeColors.disabled,
            borderColor: isDarkMode ? '#1e293b' : '#e2e8f0',
            opacity: 0.9,
        },
        datePickerButton: {
            backgroundColor: activeColors.card,
            borderRadius: 12,
            borderWidth: 1,
            borderColor: activeColors.border,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.05,
            shadowRadius: 4,
            elevation: 2,
            flexDirection: 'row',
            alignItems: 'center',
            paddingHorizontal: 16,
            paddingVertical: 14,
        },
        textInput: {
            paddingHorizontal: 16,
            paddingVertical: 14,
            fontSize: 16,
            color: activeColors.text,
            backgroundColor: 'transparent',
        },
        dateButtonText: {
            fontSize: 16,
            color: activeColors.text,
        },
        textInputMultiline: {
            minHeight: 100,
            textAlignVertical: 'top',
        },
        buttonContainer: {
            position: 'absolute',
            bottom: 0,
            left: 0,
            right: 0,
            flexDirection: 'row',
            paddingHorizontal: 20,
            paddingVertical: 20,
            backgroundColor: activeColors.card,
            borderTopWidth: 1,
            borderTopColor: activeColors.border,
        },
        prevButton: {
            flexDirection: 'row',
            alignItems: 'center',
            paddingHorizontal: 20,
            paddingVertical: 14,
            borderRadius: 12,
            borderWidth: 1,
            borderColor: activeColors.border,
            backgroundColor: activeColors.card,
            marginRight: 12,
        },
        prevButtonText: {
            fontSize: 16,
            color: activeColors.subtext,
            fontWeight: '600',
            marginLeft: 4,
        },
        nextButton: {
            flex: 1,
            borderRadius: 12,
            overflow: 'hidden',
        },
        nextButtonFull: {
            marginLeft: 0,
        },
        nextButtonGradient: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            paddingVertical: 16,
            paddingHorizontal: 24,
        },
        nextButtonText: {
            color: '#ffffff',
            fontSize: 16,
            fontWeight: '700',
            marginRight: 4,
        },
        imagePreview: {
            width: '100%',
            height: '100%',
            borderRadius: 6,
        },
        imagePickerText: {
            color: activeColors.subtext,
            fontSize: 16,
            textAlign: 'center',
        },
        imagePickerButton: {
            width: '60%',
            height: 150,
            borderRadius: 6,
            borderWidth: 1,
            borderColor: activeColors.border,
            alignItems: 'center',
            justifyContent: 'center',
            backgroundColor: activeColors.card,
            marginTop: 3,
            marginBottom: 6,
            alignSelf: 'flex-start',
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.18,
            shadowRadius: 6,
            elevation: 6,
        },
        imagePreviewContainer: {
            width: '100%',
            height: '100%',
            justifyContent: 'center',
            alignItems: 'center',
        },
        removeImageButton: {
            position: 'absolute',
            top: 4,
            right: 4,
            backgroundColor: isDarkMode ? 'rgba(30, 41, 59, 0.8)' : 'rgba(255, 255, 255, 0.8)',
            borderRadius: 14,
        },
    });
};
